blank_issues_enabled: false
contact_links:
  - name: â“ Help and Support Discord Channel
    url: https://discord.gg/ZeEq5TE
    about: Bug reports: Permasigner -> support; Feature requests: Permasigner -> contribution
